services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspaces/dorea-workspace:cached
      - dorea-pip-cache:/root/.cache/pip
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  dorea-pip-cache:
